SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `role`;
DROP TABLE IF EXISTS `category`;
DROP TABLE IF EXISTS `movies_has_users`;
DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `movies`;
DROP TABLE IF EXISTS `comment`;
SET FOREIGN_KEY_CHECKS=1;